### ISSUE TITLE
PWAできるか試す

### ISSUE THREAD

**Issue by KOU050223** [jyogi-web/yanbaru-react-pwa#1]

**Comment by KOU050223** [comment]
https://red-grass-08143c200.5.azurestaticapps.net/

**Comment by Yanai1005** [comment]
https://w3c.github.io/deviceorientation/spec-source-orientation.html

**Comment by Yanai1005** [comment]
https://w3c.github.io/deviceorientation/spec-source-orientation.html#scope
https://developer.mozilla.org/ja/docs/Web/API/DeviceMotionEvent
https://blog.kimizuka.org/entry/2021/08/04/231525
https://moriokalab.com/news/63

**Comment by Yanai1005** [comment]
なんか値が取れたのでClose
